name = "Apex"
grammar = "apex"
path_suffixes = ["cls"]
line_comments = ["//"]
autoclose_before = ";:.,=}])>` \n\t\""
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
]
